### ISSUE TITLE
Package not installable in a .NET Core app

### ISSUE THREAD

**Issue by ExplodingCabbage** [ilyabreev/Bia.Countries#16]
If I create a new .NET Core console app and try to install this package, it fails:

```
PM> Install-Package Bia.Countries -Version 2.0.2
  GET https://api.nuget.org/v3/registration2-gz/bia.countries/index.json
  OK https://api.nuget.org/v3/registration2-gz/bia.countries/index.json 443ms
Restoring packages for \\mac\home\documents\visual studio 2017\Projects\Test\Test\Test.csproj...
Install-Package : Package Bia.Countries 2.0.2 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Bia.Countries 2.0.2 supports: net40 
(.NETFramework,Version=v4.0)
At line:1 char:1
+ Install-Package Bia.Countries -Version 2.0.2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with .NETCoreApp,Version=v1.1.
At line:1 char:1
+ Install-Package Bia.Countries -Version 2.0.2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'Test'.
At line:1 char:1
+ Install-Package Bia.Countries -Version 2.0.2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:01.1153630
```

Would be great to get .NET Core support if possible!

**Comment by ilyabreev** [comment]
Yeah it would be great. It seems like project needs some multi targeting.
Feel free to submit a PR if you'd like to participate.

**Comment by niemyjski** [comment]
would be great to have netstandard 2 support

**Comment by tinohager** [comment]
I have send a pull request for .netstandard 2.0 support https://github.com/ilyabreev/Bia.Countries/pull/17

**Comment by ilyabreev** [comment]
@tinohager Thank you! Requested little change on it.

**Comment by tinohager** [comment]
@ilyabreev when do you publish a new nuget package?

**Comment by ilyabreev** [comment]
Can't build the solution.
```
1>C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly.
1>C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
1>C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ReferenceInfo.GetVersion(ITaskItem referencePath)
1>C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ReferenceInfo.CreateReferenceInfo(ITaskItem referencePath)
1>C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ReferenceInfo.CreateReferenceInfos(IEnumerable`1 referencePaths)
1>C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore()
1>C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
1>C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by tinohager** [comment]
Build with the lastest version of visual studio 2017 for windows?

**Comment by ilyabreev** [comment]
15.3
latest is 15.4
I'll try to update and build with 15.4

ср, 11 окт. 2017 г. в 9:41, Tino Hager <notifications@github.com>:

**Comment by tinohager** [comment]
maybe also important install the powershell tools https://marketplace.visualstudio.com/items?itemName=AdamRDriscoll.PowerShellToolsforVisualStudio2017-18561

**Comment by ilyabreev** [comment]
Update to the 15.4 and installing posh tools helped to build the solution.
Just bumped 3.0.0 to nuget.
